### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Ispahan** [jpoffline/smethod#1]

**Comment by michaelkopp** [comment]
I just cloned and ran the notebook in Mathematica 9.0.0 and 10.1 without error.
What Mathematica version do you use? 

The error message sounds like there is some problem with the Manipulate function in the plotting section of the notebook.

Can let me know in which part of the notebook creates the error message? 

Note that if you only want to evaluate the “plotting" part of the notebook you still need to evaluate the first cell of the “calculating” section in order to define hbar and bs, etc.

**Comment by Ispahan** [comment]
I use mathematica 10
I think this line: 
Manipulate[ Plot[{1 + DelInt[x, a]}, {x, -10, 10}, PlotRange -> All], {a, amin,  amax}]

and the one after this one are creating the error. The calculating part does not cause any errors.

**Comment by michaelkopp** [comment]
Have you tried plotting the functions without Manipulate, simply by putting some values for the scale factor like

Plot[{1 + DelInt[x, amin]}, {x, -10, 10}, PlotRange -> All]
Plot[{1 + DelInt[x, amax]}, {x, -10, 10}, PlotRange -> All]

If this doesn�t work either, maybe you corrupted the the files that are read in (like SchroedingerPsi1e-4.m). 
You can test this quickly be testing whether amin and amax have numerical values.

**Comment by Ispahan** [comment]
I think I found the problem. I did not have the notebook´s kernel
set to local. The program seems to be running now.
How long do you think it approx needs to run?

**Comment by michaelkopp** [comment]
It takes a very long time (about 6 h). This notebook is definitely not useful for any serious application and is why a fast c++ code should be developed, which is of course the intention of this git project!
The mathematica files were intended to check and compare the solution from the c++ version.

**Comment by Ispahan** [comment]
I have a question, do the figures that this code produces look like 
figure 1 in this paper: 1403.5567v1 (Cora Uhlemann)
If not do you have the code which shows theses results?

**Comment by Ispahan** [comment]
Hello again,

The schroedingermethodpancake.nb has been running for over 6 hours now.
I have made screenshots of the progress. I dont understand why in the plotting section
of the code I am only seeing two large grey squares instead of a developing plot.
![sss3](https://cloud.githubusercontent.com/assets/12594477/8684769/7daba6ae-2a7a-11e5-8574-8c7c45cba9e6.png)
![sss2](https://cloud.githubusercontent.com/assets/12594477/8684772/837be062-2a7a-11e5-83d5-9b4e803e2efd.png)

Maybe you see what the problem is.

**Comment by michaelkopp** [comment]
To answer your last question:
This notebook does not contain the commands to construct the Husimi distribution shown in Fig 1.
At the moment I don’t have the time to clean up the file that produced those plots.
For this you need to take the solution psi(x,t), construct psi_H(x,p,t) and square it to get f_H(x,p,t).

Regarding your more recent question and your screen shots: it seems that the calculation has not finished yet, in particular the cells of the grey `Manipulate' command have not evaluated so they don’t and can’t show anything.

Inside the Manipulate |psi(x,a)|^2 and the phase are plotted as a function of x, and Manipulate allows to show the function at different a.

Note that you don’t have to run the “Calculating” part of the code in order to evaluate the “Plotting” part. The necessary files are included in the github folder and are read in using ‘Import’.
The construction of the unwrapped phase “PhiInt” requires that 'hbar' and 'bs' have numerical values, so you should evaluate the cell with the constants first, skip the “calculation” part and evaluate the plotting part, in case you only want to see the ‘Manipulate' movie.

To make it simpler I attached a notebook that exactly does what I just described. Put into the same folder as the original mathematica file and evaluate it. Make sure that SchroedingerPsi1e-4.m is intact (by downloading it again from github)

**Comment by Ispahan** [comment]
I am sorry to have bothered you with my first question. You were right it executed just fine
and the results look great. Thank you so much.

Back to my second question I am really interested to see how you plotted this Husimi distribution.
If you have some time available I would really like to see this file you spoke of, which plots this
distribution.

Thank you so much for answering my questions with such patience.

**Comment by Ispahan** [comment]
Hello again,

I have been playing a little with you mathematica code. I only seem to get results
when I run the entire notebook. When I run only the Plotting cell I am left with empty axes
after 6 hours of running.
Do you have any idea why?

Cheers

**Comment by michaelkopp** [comment]
Did you try the Mathematica file send you last time?
Did you download freshly  from github the file that is read in?

By the way: I got the impression that you don't have much experience with Mathematica. You might profit from looking at some introductory Mathematica tutorial first, before you try to understand this notebook.

**Comment by Ispahan** [comment]
I have not tried to donwload it freshly from Github. I will try that too.

You are right I am new to Mathematica, I have however invested some time in
introductory
tutorials. I am used to Python and C, I did however ask some experienced
Mathematica users
about the empty axes, and they could not figure out why the results are
empty axes when I only run
the Plotting cells.
That´s why I am bothering you with these questions.

Thank you for your help, I will try your suggestions

2015-07-23 9:46 GMT+02:00 michaelkopp <notifications@github.com>:

**Comment by Ispahan** [comment]
I somehow can not find the file you attached to an earlier question I had?
Could you please send it to me again?

**Comment by Ispahan** [comment]
​Hello,

Could you pelase send me this notebook (which does only the calculating
part) you spoke of a few comments earlier.
I think you forgot to include it in you comment.​

Thank you.

2015-07-23 11:35 GMT+02:00 I Bouisaghouane <i.bouisaghouane@gmail.com>:

**Comment by Ispahan** [comment]
Hello again,

I have a few questions if you have time. So I have tried to analyse the results
from the Schrodinger pancake collapse and I am wondering how I can incorporate 
the Zeldovich pancake collapse into the schrodinger pancake collapse
for comparison. Similar to what Spencer and Cole (2003) have done in their paper.

**Comment by michaelkopp** [comment]
Hallo,
I am not sure what exactly you mean by "incorporate". 
In 1D, the Zel'dovich approximation the exact solution up to the time of shell crossing is Eq 52 of Coles and Spencer.
This allows you to compare for instance the density profiles.

If you continue the solution after shell crossing, you get those two separating spikes in the density profile in Fig.1 of Coles and Spencer.
The interesting thing they notice is: if you use in the Schrödinger equation not the correct Newtonian potential, but simply its initial value, the wave function nearly behaves like the Zel'dovich approximation. In particular after shell crossing the two separating density peaks are present.
That they are similar before shell crossing is not surprising, since the Newtonian potential is to a good approximation constant.
But it also shows how important this tiny time dependence of the Newtonian potential is: it is responsible for holding the wave function together in Fig. 2

**Comment by Ispahan** [comment]
I meant how can I plot the equation 52 in the same graph
as the schrodingerpancakecollapse in the mathematica code?

**Comment by michaelkopp** [comment]
By request of Ispahan I deleted all my replies to his comments.

**Comment by Ispahan** [comment]
Thank you I will try that!

**Comment by Ispahan** [comment]
Hello,

I have tried to adjust and put the line you suggested into the SchrodingerMethodPancakeOnlyPlotting.nb. I have not been able to plot it properly,
I am left with empty axes and I am not sure what to do about it.
I want to adjust the onlyplotting notbook to include the zeldovich pancake collapse
together with the schrodinger collapse in 1 plot.
So I want to add add a line similar to ParametricPlot[{x[q,aini], delta[q,aini]},{q,-10,10} ], to the nb
and have the result plotted together with the other two schrodinger collapse plots in which I can
adjust the scale parameter. So I want to be able to adjust the scale parameter for the zeldovich pancake collapse as well.
Can you help me?
